bot_0:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinoir@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1500, 1549]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus


bot_1:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql0@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1550, 1599]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_2:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/alexanderborchun@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1600, 1649]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_3:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/karvinior@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1650, 1699]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_4:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/rxmzge8117@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1700, 1749]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_5:
  project: hypos_norm
  subproject: gen
  site: qwen
  mode: web_search_no_think
  model: qwen
  scenario: web_search_no_think
  browser_master_profile: ~/dsmldlql@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 5.0
  row_range: [1750, 1799]
  max_questions: 100
  restart_delay: 0
  proxy: None
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus



bot_10:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/janskisheikh042@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 60.0
  row_range: [1321, 1449]
  max_questions: 400
  restart_delay: 0
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus


bot_11:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/halseycusenza35@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 55.0
  row_range: [1450, 1575]
  max_questions: 400
  restart_delay: 0
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus

bot_12:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/rxmzge8117@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 45.0
  row_range: [1287, 1320]
  max_questions: 200
  restart_delay: 0
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_go

bot_13:
  project: hypos_norm
  subproject: gen
  site: gpt
  mode: web_search
  model: gpt
  scenario: web_search
  browser_master_profile: ~/kacalbsullo03467p@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 55.0
  row_range: [1575, 1699]
  max_questions: 400
  restart_delay: 0
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gpt_plus




bot_20:
  project: hypos_norm
  subproject: gen
  site: gemini
  mode: thinking
  model: gemini
  scenario: thinking_1
  browser_master_profile: ~/vanthuan1990t@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 220.0
  row_range: [700, 949]
  max_questions: 300
  restart_delay: 0
  proxy: [186.65.122.102, 8000, "bbaBmV", "vEyoqs"]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gemini_plus

bot_21:
  project: hypos_norm
  subproject: gen
  site: gemini
  mode: thinking
  model: gemini
  scenario: thinking_0
  browser_master_profile: ~/hoanghao1994hy@gmail.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 220.0
  row_range: [941, 949]
  max_questions: 300
  restart_delay: 0
  proxy: [186.65.122.102, 8000, "bbaBmV", "vEyoqs"]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"
  subscription: gemini_plus




bot_3_:
  project: hypos_norm
  subproject: gen
  site: claude
  mode: pro
  model: claude
  scenario: sonnet
  browser_master_profile: ~/leinswdolenfnk4@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 150
  row_range: [950, 1199]
  max_questions: 300
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_4_:
  project: hypos_norm
  subproject: gen
  site: claude
  mode: pro
  model: claude
  scenario: sonnet
  browser_master_profile: ~/sweetozewdur0ye@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 150
  row_range: [324, 325]
  max_questions: 100
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_5_:
  project: hypos_norm
  subproject: gen
  site: claude
  mode: pro
  model: claude
  scenario: sonnet
  browser_master_profile: ~/touchxdimespgq6d4@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 150
  row_range: [337, 337]
  max_questions: 100
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

bot_6_:
  project: hypos_norm
  subproject: gen
  site: claude
  mode: pro
  model: claude
  scenario: sonnet
  browser_master_profile: ~/meachjhayamegl@outlook.com
  dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
  columns:
    - uid
    - query
    - used
  roi: [0, 0, 960, 800]
  cooldown: 1.0
  question_interval: 150
  row_range: [338, 338]
  max_questions: 100
  restart_delay: None
  proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
  schedule:
    start_immediately: true
    start_times:
      - "00:00"
      - "06:00"
      - "12:00"
      - "18:00"

# bot_1:
#   project: hypos_norm
#   subproject: gen
#   site: gpt
#   mode: web_search
#   model: gpt
#   scenario: web_search
#   browser_master_profile: ~/halseycusenza35@outlook.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 55.0
#   row_range: [1100, 1199]
#   max_questions: 400
#   restart_delay: 0
#   proxy: [186.65.122.102, 8000, bbaBmV, vEyoqs]
#   schedule:
#     start_immediately: true
#     start_times:
#       - "00:00"
#       - "06:00"
#       - "12:00"
#       - "18:00"
#   subscription: gpt_plus


# bot_6_:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_7_:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_8:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_9:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_10:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_11:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_12:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_13:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_14:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_15:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_16:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_17:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_18:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600

# bot_19:
#   project: hypos_norm
#   subproject: gen
#   site: qwen
#   mode: web_search_no_think
#   model: qwen
#   scenario: web_search_no_think
#   browser_master_profile: ~/dsmldlql_gmail.com
#   dataset_path: datasets/sp_depers_final_with_hypnorm_used_marks.csv
#   columns:
#     - uid
#     - query
#     - used
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [516, 525]
#   max_questions: 100
#   restart_delay: 3600


# bot_20:
#   project: hypos_norm
#   subproject: gen
#   site: gpt
#   mode: study_learn
#   model: gpt
#   browser_master_profile: ~/bot_master_profile
#   roi: [0, 621, 500, 620]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [0, 100]
#   max_questions: 100
#   restart_delay: 3600

# bot_21:
#   project: hypos_norm
#   subproject: gen
#   site: perplexity
#   mode: grok
#   model: perplexity_grok
#   scenario: grok
#   browser_master_profile: ~/bot_master_profile
#   roi: [0, 0, 960, 800]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [124, 148]
#   max_questions: 100
#   restart_delay: 3600

# bot_22:
#   project: hypos_norm
#   subproject: gen
#   site: perplexity
#   mode: grok
#   model: perplexity_grok
#   browser_master_profile: ~/bot_master_profile
#   roi: [0, 621, 500, 620]
#   cooldown: 1.0
#   question_interval: 5.0
#   row_range: [163, 189]
#   max_questions: 100
#   restart_delay: 3600