bot_0:
  browser_master_profile: /home/profiles/bot_0/default_profile
  columns:
  - uid
  - query
  - used
  cooldown: 1.0
  dataset_path: datasets/sp_after_2000_good.csv
  max_questions: 150
  mode: web_search_no_think
  model: qwen
  project: hypos_norm
  proxy: None
  question_interval: 5.0
  restart_delay: 0
  roi:
  - 0
  - 0
  - 960
  - 800
  row_range:
  - 2051
  - 2100
  scenario: web_search_no_think
  schedule:
    start_immediately: true
    start_times:
    - 00:00
    - 06:00
    - '12:00'
    - '18:00'
  site: qwen
  subproject: gen
  subscription: gpt_plus
